### ISSUE TITLE
Can't get it running on Windows

### ISSUE THREAD

**Issue by d-krupke** [d-krupke/skbuild-conan#4]
I tried to get this running on a Windows machine and GitHub Workflow with Windows image, but it fails. Not sure if it is the general setup or a problem with skbuild_conan. I actually think that the problem may be with MSVC and scikit-build, but I would like how to get it working again. It seemed to be working before packaging the tricks into skbuild_conan.

**Comment by Racopokemon** [comment]
Adding a certain cmake argument in the project [https://github.com/d-krupke/pyvispoly](https://github.com/d-krupke/pyvispoly) possibly solved an issue with cmake backwards compatibility for MSVC. However, the build still fails on my machine. 

```
cmake_args=["-DCMAKE_POLICY_DEFAULT_CMP0091=NEW"],
```

**Comment by d-krupke** [comment]
Working now.
